<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-21 11:13

import django.db.models.deletion
=======
# Generated by Django 5.2.3 on 2025-07-03 12:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
=======
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administradores'), ('Cadastro', 'Cadastrados')], default='Cadastro', max_length=15)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('groups', models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido. Formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('iest', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('situacao_cadastral', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=10)),
                ('tipo_empresa', models.CharField(blank=True, choices=[('cadastrado', 'cadastrados')], max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_juridica', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
=======
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Razão Social ou Nome Completo', max_length=255, verbose_name='Nome Completo')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
=======
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Transportadora')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['nome'],
            },
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
        ),
        migrations.CreateModel(
            name='ValePallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vale', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField()),
                ('qtd_pbr', models.PositiveIntegerField(default=0)),
                ('qtd_chepp', models.PositiveIntegerField(default=0)),
<<<<<<< HEAD
                ('saldo_pbr', models.PositiveIntegerField(default=0)),
                ('saldo_chepp', models.PositiveIntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('UTILIZADO', 'Utilizado'), ('RETORNADO', 'Retornado'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hash_seguranca', models.CharField(editable=False, max_length=32, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.motorista')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.transportadora')),
            ],
=======
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('SAIDA', 'Saida'), ('RETORNO', 'Retorno'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hash_seguranca', models.CharField(editable=False, max_length=32, unique=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.cliente')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_criados', to='app_controller.pessoajuridica', verbose_name='Criado por')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.motorista')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.transportadora')),
                ('usuario_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_retorno', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Retorno')),
                ('usuario_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_saida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da saída')),
            ],
            options={
                'verbose_name': 'Vale Pallet',
                'verbose_name_plural': 'Vales Pallets',
                'ordering': ['-data_emissao'],
            },
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('RETORNO', 'Retorno')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('qtd_pbr', models.PositiveIntegerField(default=0)),
                ('qtd_chepp', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controller.valepallet')),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-data_hora'],
            },
        ),
=======
                ('tipo', models.CharField(choices=[('EMITIDO', 'Emitido'), ('SAIDA', 'Saida'), ('RETORNO', 'Retorno'), ('CANCELADO', 'Cancelado'), ('SCAN', 'Scan QR Code')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField(blank=True, null=True)),
                ('qtd_pbr', models.PositiveIntegerField(default=0)),
                ('qtd_chepp', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controller.valepallet')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['nome'], name='app_control_nome_eb8313_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cpf'], name='app_control_cpf_da29e4_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='app_control_nome_0e455e_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cnpj'], name='app_control_cnpj_ed8a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transportadora',
            index=models.Index(fields=['nome'], name='app_control_nome_14b15f_idx'),
        ),
        migrations.AddIndex(
            model_name='transportadora',
            index=models.Index(fields=['cnpj'], name='app_control_cnpj_41431c_idx'),
        ),
>>>>>>> c4adc9abb5167d69417fb69affbbc97fdcd30829
    ]
